.

diff --git a/.github/workflows/ios_navigation_tests.yml b/.github/workflows/ios_navigation_tests.yml
--- a/.github/workflows/ios_navigation_tests.yml
+++ b/.github/workflows/ios_navigation_tests.yml
@@ -34,12 +34,12 @@ jobs:
 
       - name: Boot iPhone 15 Pro (iOS 17.2) Simulator
         run: |
-          UDID=$(xcrun simctl list devices available | grep -i "iPhone 15 Pro" | grep -i "17.2" | awk -F'[()]' '{print $2}' | head -n 1)
-          if [ -z "$UDID" ]; then
-            echo "::error::No matching iPhone 15 Pro (iOS 17.2) simulator found!"
-            exit 1
-          fi
-
+          #UDID=$(xcrun simctl list devices available | grep -i "iPhone 15 Pro" | grep -i "17.2" | awk -F'[()]' '{print $2}' | head -n 1)
+          #if [ -z "$UDID" ]; then
+          #  echo "::error::No matching iPhone 15 Pro (iOS 17.2) simulator found!"
+          #  exit 1
+          #fi
+          UDID=5C4114F9-8311-49E4-A834-4E4ABEDE918F
           echo "Booting simulator with UDID: $UDID"
           xcrun simctl boot "$UDID" || echo "Simulator might already be booted"
           xcrun simctl bootstatus "$UDID" -b
