remove ios ui tests

diff --git a/.github/workflows/ios_navigation_tests.yml b/.github/workflows/ios_navigation_tests.yml
--- a/.github/workflows/ios_navigation_tests.yml
+++ b/.github/workflows/ios_navigation_tests.yml
@@ -17,42 +17,42 @@ jobs:
       - name: 🧾 Checkout repo
         uses: actions/checkout@v4
 
-      - name: 🔧 Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: '20'
+      # - name: 🔧 Set up Node.js
+      #   uses: actions/setup-node@v4
+      #   with:
+      #     node-version: '20'
 
       - name: 🔧 Set up .NET
         uses: actions/setup-dotnet@v4
         with:
           dotnet-version: '9.0.x'
 
-      - name: 📦 Install Appium + XCUITest driver
-        run: |
-          npm install -g appium
-          appium driver install xcuitest
+      # - name: 📦 Install Appium + XCUITest driver
+      #   run: |
+      #     npm install -g appium
+      #     appium driver install xcuitest
 
-      - name: 🧹 Clean DerivedData and WDA cache
-        run: |
-          rm -rf ~/Library/Developer/Xcode/DerivedData
-          rm -rf ~/.appium/node_modules/appium-webdriveragent/Build
+      # - name: 🧹 Clean DerivedData and WDA cache
+      #   run: |
+      #     rm -rf ~/Library/Developer/Xcode/DerivedData
+      #     rm -rf ~/.appium/node_modules/appium-webdriveragent/Build
 
-      - name: 🧪 Start Appium Server
-        run: |
-          nohup appium --log appium.log &
+      # - name: 🧪 Start Appium Server
+      #   run: |
+      #     nohup appium --log appium.log &
 
-      - name: 📱 Create iOS Simulator (if needed)
-        run: |
-          SIMULATOR_NAME="ci-sim-$RANDOM"
-          xcrun simctl create "$SIMULATOR_NAME" "$DEVICE_NAME" "com.apple.CoreSimulator.SimRuntime.iOS-${PLATFORM_VERSION//./-}"
-          echo "SIMULATOR_NAME=$SIMULATOR_NAME" >> $GITHUB_ENV
+      # - name: 📱 Create iOS Simulator (if needed)
+      #   run: |
+      #     SIMULATOR_NAME="ci-sim-$RANDOM"
+      #     xcrun simctl create "$SIMULATOR_NAME" "$DEVICE_NAME" "com.apple.CoreSimulator.SimRuntime.iOS-${PLATFORM_VERSION//./-}"
+      #     echo "SIMULATOR_NAME=$SIMULATOR_NAME" >> $GITHUB_ENV
 
-      - name: 🚀 Boot simulator
-        run: |
-          xcrun simctl boot "$SIMULATOR_NAME"
-          SIMULATOR_ID=$(xcrun simctl list | grep 'Booted' | awk -F '[()]' '{print $2}')
-          echo "SIMULATOR_ID=$SIMULATOR_ID"
-          echo "SIMULATOR_ID=$SIMULATOR_ID" >> $GITHUB_ENV          
+      # - name: 🚀 Boot simulator
+      #   run: |
+      #     xcrun simctl boot "$SIMULATOR_NAME"
+      #     SIMULATOR_ID=$(xcrun simctl list | grep 'Booted' | awk -F '[()]' '{print $2}')
+      #     echo "SIMULATOR_ID=$SIMULATOR_ID"
+      #     echo "SIMULATOR_ID=$SIMULATOR_ID" >> $GITHUB_ENV          
      
       - name: Install MAUI Workloads
         run: |
@@ -65,30 +65,30 @@ jobs:
       - name: Build Code
         run: dotnet build TransactionMobile.Maui/TransactionMobile.Maui.csproj  -f net9.0-ios -c Release --no-restore
 
-      - name: find the app
-        run: |
-            find /Users/runner/work -name "*.app"
-            mkdir -p /Users/runner/work/mobileapp
-            cp -R /Users/runner/work/TransactionMobile/TransactionMobile/TransactionMobile.Maui/bin/Release/net9.0-ios/iossimulator-arm64/TransactionMobile.Maui.app /Users/runner/work/mobileapp/
+      # - name: find the app
+      #   run: |
+      #       find /Users/runner/work -name "*.app"
+      #       mkdir -p /Users/runner/work/mobileapp
+      #       cp -R /Users/runner/work/TransactionMobile/TransactionMobile/TransactionMobile.Maui/bin/Release/net9.0-ios/iossimulator-arm64/TransactionMobile.Maui.app /Users/runner/work/mobileapp/
 
-      - name: verify the app
-        run: |
-            codesign -dvvv /Users/runner/work/mobileapp/TransactionMobile.Maui.app || echo "Not signed"
-            plutil -p /Users/runner/work/mobileapp/TransactionMobile.Maui.app/Info.plist | grep CFBundleIdentifier
+      # - name: verify the app
+      #   run: |
+      #       codesign -dvvv /Users/runner/work/mobileapp/TransactionMobile.Maui.app || echo "Not signed"
+      #       plutil -p /Users/runner/work/mobileapp/TransactionMobile.Maui.app/Info.plist | grep CFBundleIdentifier
 
       #- name: run the app
       #  run: |
       #      xcrun simctl install booted /Users/runner/work/mobileapp/TransactionMobile.Maui.app
       #      xcrun simctl launch booted com.transactionprocessing.pos
       
-      - name: Run iOS Navigation Tests
-        run: dotnet test TransactionMobile.Maui.UiTests/TransactionMobile.Maui.UiTests.csproj --filter "(Category=PRNavTest)&(Category=iOS)" --no-restore
+      #- name: Run iOS Navigation Tests
+      #  run: dotnet test TransactionMobile.Maui.UiTests/TransactionMobile.Maui.UiTests.csproj --filter "(Category=PRNavTest)&(Category=iOS)" --no-restore
 
-      - name: Upload Appium Logs on Failure      
-        if: failure()
-        uses: actions/upload-artifact@v4
-        with:
-           name: ios-software_navigation_tests_appium
-           path: appium.log
+      #- name: Upload Appium Logs on Failure      
+      #  if: failure()
+      #  uses: actions/upload-artifact@v4
+      #  with:
+      #     name: ios-software_navigation_tests_appium
+      #     path: appium.log
 
   
