1

diff --git a/.github/workflows/pr for ios.yml b/.github/workflows/pr for ios.yml
--- a/.github/workflows/pr for ios.yml
+++ b/.github/workflows/pr for ios.yml
@@ -21,35 +21,22 @@ jobs:
       - name: Test IP
         run: echo $ENV_IPADDRESS
 
-      - name: Uninstall Docker Desktop if present
+      - name: Ensure Docker Desktop is running (Background)
         run: |
-          brew uninstall --cask docker || true
-          sudo killall -9 Docker || true
-          sudo rm -rf /Applications/Docker.app /usr/local/bin/docker-compose /var/run/docker.sock
-
-      - name: Install Docker CLI and dependencies
-        run: |
-          brew install docker docker-compose docker-buildx
-          brew link --overwrite docker
-
-      - name: Start Docker Daemon as a background process
-        run: |
-          nohup sudo dockerd > ~/docker.log 2>&1 &
-
-          # Retry loop for up to 60 seconds
-          timeout=60
-          while ! docker info &>/dev/null; do
-            sleep 5
-            timeout=$((timeout - 5))
-            echo "Waiting for Docker to start..."
-            if [ "$timeout" -le 0 ]; then
-              echo "Docker did not start within 60 seconds, exiting."
-              cat ~/docker.log
-              exit 1
+          # Check if Docker Desktop is running
+          if pgrep -x "Docker" > /dev/null; then
+            echo "Docker Desktop is already running."
+          else
+            echo "Starting Docker Desktop..."
+            open -a Docker & # Start Docker Desktop in the background
+            sleep 20 # Wait for Docker Desktop to start. Adjust the sleep time if needed.
+            #Verify docker is running
+            if ! docker info &>/dev/null; then
+                echo "Docker Desktop failed to start correctly."
+                exit 1
             fi
-          done
-
-          echo "Docker is running!"
+            echo "Docker Desktop started successfully."
+          fi
 
       - name: Verify Docker Installation
         run: |
